version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: '.github:'
    labels:
      - 'deps'
      - 'gha'
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'go.mod:'
    labels:
      - 'deps'
      - 'go'
