tabWidth: 2
semi: false
singleQuote: true
proseWrap: 'always'
bracketSpacing: false
trailingComma: 'none'
printWidth: 80
overrides:
  - files: '*.html'
    options:
      parser: 'go-template'
      printWidth: 140
