#!/usr/bin/env bash

# Install a command from astrophena/exp. gh with authentication is required.
# Use it like this:
#
#  $ curl -fsSL https://astrophena.name/exp/install | bash -s -- <cmd> [dir]
#

if test -z "$BASH_VERSION"; then
	echo "Please run this script using bash, not sh or any other shell." >&2
	exit 1
fi

# We wrap the entire script in a big function which we only call at
# the very end, in order to protect against the possibility of the
# connection dying mid-script.

set -euo pipefail

_() {
	TMP="$(mktemp -d)"
	cleanup() {
		rm -rf "$TMP"
	}
	trap cleanup EXIT

	[[ -z "${1:-}" ]] && {
		echo "usage: curl -fsSL https://astrophena.name/exp/install | bash -s -- <cmd> [dir]"
		exit 1
	}
	name="$1"
	dir="${2:-$PWD}"

	case "$(uname -o)" in
	"GNU/Linux" | "Linux")
		goos="linux"
		;;
	"Android")
		goos="android"
		;;
	*)
		echo "Your OS is unsupported."
		exit 1
		;;
	esac

	case "$(uname -m)" in
	"x86_64")
		goarch="amd64"
		;;
	"aarch64")
		goarch="arm64"
		;;
	*)
		echo "Your architecture is unsupported."
		exit 1
		;;
	esac

	cd "$TMP"
	gh run download -n "$name-$goos-$goarch" -R astrophena/exp
	chmod +x "$TMP/$name"
	mv "$TMP/$name" "$dir"
}

# Now that we know the whole script has downloaded, run it.
_ "$@"
