#!/bin/sh

echo "==> Running pre-commit check..."
go generate      # update copyrights
go test -count=1 # to invalidate test cache
go test ./internal/...
go mod tidy --diff || {
	echo "run 'go mod tidy' before committing"
	exit 1
}
