#!/usr/bin/env bash

set -euo pipefail
cd "$(dirname $0)/.."
source script/.shared

if ! command -v prettier &>/dev/null; then
	info "==> Installing Prettier..."
	npm install -g prettier prettier-plugin-go-template
fi
go_install actionlint github.com/rhysd/actionlint/cmd/actionlint
go_install goimports golang.org/x/tools/cmd/goimports
go_install shfmt mvdan.cc/sh/v3/cmd/shfmt
go_install staticcheck honnef.co/go/tools/cmd/staticcheck
