#!/usr/bin/env bash

# © 2022 Ilya Mateyko. All rights reserved.
# Use of this source code is governed by the MIT
# license that can be found in the LICENSE file.

set -euo pipefail
cd "$(dirname $0)/.."

script/bootstrap
goimports -d .
shfmt -d .
node_modules/.bin/prettier --loglevel error --check .
