#!/usr/bin/env bash

set -euo pipefail
if [[ ! -L "$0" ]]; then
	cd "$(dirname $0)/.."
else
	# Symlinked. Called from a Git hook.
	GIT_HOOK="true"
	cd "$(dirname $0)/../.."
fi

no_color='\033[0m'
yellow_color='\033[0;33m'

info() {
	echo -e "${yellow_color}"$@"${no_color}"
}

script/bootstrap

if [[ ! -z "${CI:-}" ]] || [[ ! -z "${GIT_HOOK:-}" ]]; then
	info "==> Linting..."
	goimports -d .
	shfmt -d .
	prettier --check --loglevel warn .
	actionlint
else
	info "==> Formatting..."
	goimports -w .
	shfmt -w .
	prettier --write --loglevel warn .
fi

info "==> Running the tests..."
staticcheck ./...
# Show 'go test' output only if it failed.
set +e
out="$(go test ./... 2>&1)"
[[ "$?" != "0" ]] && echo >&2 "$out"
set -e
