#!/usr/bin/env bash

set -euo pipefail
if [[ ! -L "$0" ]]; then
	cd "$(dirname $0)/.."
else
	# Symlinked. Called from a Git hook.
	GIT_HOOK="true"
	cd "$(dirname $0)/../.."
fi

script/bootstrap

prettier="node_modules/.bin/prettier"

if [[ ! -z "${CI:-}" ]] || [[ ! -z "${GIT_HOOK:-}" ]]; then
	echo "==> Linting..."
	goimports -d .
	shfmt -d .
	"$prettier" --check --loglevel warn .
else
	echo "==> Formatting..."
	goimports -w .
	shfmt -w .
	"$prettier" --write --loglevel warn .
fi

echo "==> Running the tests..."
# Show 'go test' output only if it failed.
set +e
out="$(go test ./... 2>&1)"
[[ "$?" != "0" ]] && echo >&2 "$out"
set -e
