#!/usr/bin/env bash

set -euo pipefail
if [[ ! -L "$0" ]]; then
	cd "$(dirname $0)/.."
else
	# Symlinked. Called from a Git hook.
	cd "$(dirname $0)/../.."
fi

script/bootstrap

prettier="node_modules/.bin/prettier"

if [[ ! -z "${CI:-}" ]]; then
	echo "==> Linting..."
	goimports -d .
	shfmt -d .
	"$prettier" --check .
else
	echo "==> Formatting..."
	goimports -w .
	shfmt -w .
	"$prettier" --write .
fi

echo "==> Running the tests..."
CGO_ENABLED=0 go test
