#!/usr/bin/env bash

set -euo pipefail
cd "$(dirname $0)/.."

tmpdir="$(mktemp -d)"

cleanup() {
	rm -rf "$tmpdir"
}
trap cleanup EXIT

script/build.go "$tmpdir"
cd "$tmpdir"
zip -0 -r site.zip . >/dev/null
curl -X PUT \
	--oauth2-bearer "$(<~/.config/central/admin-token)" \
	-F content=@site.zip http://localhost:3000/update
