name: 'goupdate'
on:
  schedule:
    # Every day (at 07:00).
    - cron: '0 4 * * *'
  workflow_dispatch:
jobs:
  run:
    name: 'Run'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Check out'
        uses: 'actions/checkout@v4'
      - name: 'Set up Go'
        uses: 'actions/setup-go@v5'
        with:
          go-version-file: 'go.mod'
      - name: 'Run goupdate'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        run: './goupdate.go'
